# Generated by Django 5.0.4 on 2024-06-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Students'},
        ),
    ]
