# Generated by Django 5.0.4 on 2024-05-21 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimentdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
